<?php

namespace App\Http\Controllers;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{
    public function getLogout()
    {
        return view('login');
    }

    public function getDashboard()
    {
        return view('dashboard');
    }

    public function postSignUp(Request $request)
    {  $this->validate($request,[
       'email'=>'email|unique:users|required',
        'fname'=>'required|max:120',
        'reqd'=>'required|max:120',
        'password'=>'required|min:6',
    ]);
        $fname=$request['fname'];
        $reqd=$request['reqd'];
        $email=$request['email'];
        $password=bcrypt($request['password']);
        // TODO: Change the autogenerated stub
        $User = new User();
        $User->fname=$fname;
        $User->reqd=$reqd;
        $User->email=$email;
        $User->password=$password;
        $User->save();
        return redirect()->back();
    }
    public function postSignIn(Request $request)
    {
        $this->validate($request,[
        'email'=>'required',
        'password'=> 'required'
    ]);
         if (Auth::attempt(['email'=>$request['email'],'password'=>$request['password']]))
        {
            return redirect()->route('dashboard');
        }
        return back();
    }
    public function performlogout(Request $request)
    {
       Auth::logout();
       return redirect()->route('login');
    }
}
